<?php

/**
 * @file
 * Generated by BLT. Serves as an example of global includes.
 */

/**
 * An example global include file.
 *
 * To use this file, rename to global.settings.php.
 */

/**
 * Include settings files in docroot/sites/settings.
 *
 * If instead you want to add settings to a specific site, see BLT's includes
 * file in docroot/sites/{site-name}/settings/default.includes.settings.php.
 */
$additionalSettingsFiles = [
  DRUPAL_ROOT . "/sites/settings/docksal-memcache.settings.php",
  DRUPAL_ROOT . "/sites/settings/varnish.settings.php",
  DRUPAL_ROOT . "/sites/settings/config-splits.settings.php",
  // e.g,( DRUPAL_ROOT . "/sites/settings/foo.settings.php" )
];

foreach ($additionalSettingsFiles as $settingsFile) {
  if (file_exists($settingsFile)) {
    // phpcs:ignore
    require $settingsFile;
  }
}
