#!/usr/bin/env bash

ROOT_DIR="$(pwd)/"
LIST=$( git diff --name-only --cached --diff-filter=ACM )
PHPCS_BIN=vendor/bin/phpcs

echo "Executing .git/hooks/pre-commit..."
fin exec -T /var/www/vendor/bin/blt internal:git-hook:execute:pre-commit "${LIST}" --no-interaction

# Return the status of the last run command.
exit $?
