display:
  default:
    display_title: Máster
    display_options:
      exposed_form:
        options:
          submit_button: Buscar
          reset_button_label: Restablecer
          exposed_sorts_label: 'Ordenar por'
          sort_asc_label: Asc
          sort_desc_label: Desc
      pager:
        options:
          expose:
            items_per_page_label: 'Elementos por página'
            items_per_page_options_all_label: '- Todo -'
            offset_label: Desplazamiento
          tags:
            previous: '‹ Anterior'
            next: 'Siguiente >'
            first: '« Primero'
            last: 'Último »'
      filters:
        search_api_fulltext:
          expose:
            label: Buscar
      title: Buscar
      empty:
        area:
          content:
            value: 'No se han encontrado resultados.'
  page:
    display_options:
      menu:
        title: Buscar
