version: "2.1"

services:
  cli:
    image: wearegenuine/docksal-cli:gen1.1.0-cli2.10-php7.3
    environment:
      - DOCKSAL=true
  varnish:
    image: docksal/varnish:1.1-varnish4
  web:
    environment:
      - VIRTUAL_HOST
