#!/usr/bin/env bash

## Execute drush uli with specific alias.
DRUSH_ALIAS=${1:-@self}

if [[ `uname -s` == "Linux" ]]; then
  OPEN="xdg-open"
else
  OPEN="open"
fi

$OPEN $(fin drush $DRUSH_ALIAS uli | tr -d '\r')
